targets:
  $default:
    builders:
      drift_dev:
        generate_for:
          exclude:
            - lib
          include:
            - lib/database/*

      freezed:
        enabled: true
        generate_for:
          exclude:
            - lib
          include:
            - lib/models/*