name: qube_project
description: "QUBE Project for AIQUE Exam"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  drift: ^2.20.2
  drift_flutter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
